data = ["banana","apple","watermelon"]
it = iter(data)
first = next(it)
second = next(it)
third = next(it)
lenght1 = len(first)
lenght2 = len(second)
lenght3 = len(third)
print(first)
print(lenght1)
print(second)
print(lenght2)
print(third)
print(lenght3)